dic = {
    "Absolutely" : "Đúng vậy, chắc chắn là vậy rồi",
    "Be careful" : "Cẩn thận, chú ý",
    "Cheer up" : "Vui vẻ lên nào, phấn khởi lên nào",
    "Come here" : "Đến đây",
    "Exactly" : "Chính xác là vậy",
    "I got it" : "Tôi hiểu rồi",
    "It's a deal" : "Nhất trí thế nhé",
    "It's awful" : "Thật kinh khủng",
    "It's up to you" : "Tùy bạn",
    "Last but not least" : "Sau cùng nhưng không kém phần quan trọng",
    "Let me be" : "Kệ tôi",
    "Let me go" : "Để tôi đi",
    "Little by little" : "Từng li, từng tý",
    "Make yourself at home = Make yourself comfortable" : "Cứ tự nhiên",
    "No offense" : "Không phản đối",
    "No problem" : "Dễ thôi",
    "Not long ago" : "Cách đây không lâu",
    "One thing lead to another" : "Hết chuyện này đến chuyện khác",
    "One way or another" : "Không bằng cách này thì bằng cách khác",
    "Out of luck" : "Không may",
    "Out of order" : "Hư, hỏng",
    "Out of question" : "Không thể được",
    "Out of the blue" : "Bất ngờ, bất thình lình",
    "Out of touch" : "Không còn liên lạc",
    "Piece of cake" : "Dễ thôi mà, dễ ợt",
    "Poor thing" : "Thật tội nghiệp",
    "So what?" : "Vậy thì sao?",
    "Take it or leave it" : "Chịu hay không?",
    "Thanks a lot" : "Cảm ơn nhiều",
    "Why not?" : "Sao lại không?",
}
